DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM TB0000_SQL_HISTORY WHERE C0000_SCRIPT_NAME = '03-ddl-tb0003_failed_email.sql') THEN
        RAISE EXCEPTION 'Script 03-ddl-tb0003_failed_email.sql não foi executado. Não há nada para reverter.';
    END IF;
END $$;

REVOKE ALL ON TB0003_FAILED_EMAIL FROM "TIME-TRACKER-API";
REVOKE ALL ON SEQUENCE seq_tb0003_failed_email FROM "TIME-TRACKER-API";

DROP INDEX IF EXISTS IX0003_SQ_ID;
DROP INDEX IF EXISTS IX0003_SENT;
DROP INDEX IF EXISTS IX0003_NEXT_RETRY_AT;
DROP INDEX IF EXISTS IX0003_CREATED_AT;
DROP INDEX IF EXISTS IX0003_RECIPIENT;

DROP TABLE IF EXISTS TB0003_FAILED_EMAIL CASCADE;

DROP SEQUENCE IF EXISTS seq_tb0003_failed_email;

DELETE FROM TB0000_SQL_HISTORY WHERE C0000_SCRIPT_NAME = '03-ddl-tb0003_failed_email.sql';
