REVOKE ALL ON TB0004_USER_SESSION FROM "TIME-TRACKER-API";
REVOKE ALL ON SEQUENCE seq_tb0004_user_session FROM "TIME-TRACKER-API";

DROP INDEX IF EXISTS IX0004_SQ_ID;
DROP INDEX IF EXISTS IX0004_UPDATED_BY;
DROP INDEX IF EXISTS IX0004_CREATED_BY;
DROP INDEX IF EXISTS IX0004_EXPIRY;
DROP INDEX IF EXISTS IX0004_ACTIVE;
DROP INDEX IF EXISTS IX0004_REFRESH_TOKEN_HASH;
DROP INDEX IF EXISTS IX0004_REFRESH_TOKEN;
DROP INDEX IF EXISTS IX0004_USER_ID;

DROP TABLE IF EXISTS TB0004_USER_SESSION CASCADE;

DROP SEQUENCE IF EXISTS seq_tb0004_user_session;

DELETE FROM TB0000_SQL_HISTORY WHERE C0000_SCRIPT_NAME = '05-ddl-tb0004_user_session.sql';
