DROP INDEX IF EXISTS IX0001_UPDATED_BY;
DROP INDEX IF EXISTS IX0001_CREATED_BY;

ALTER TABLE TB0001_PERSON
DROP CONSTRAINT IF EXISTS fk_person_updated_by,
DROP CONSTRAINT IF EXISTS fk_person_created_by;

ALTER TABLE TB0001_PERSON 
DROP COLUMN IF EXISTS C0001_UPDATED_BY,
DROP COLUMN IF EXISTS C0001_CREATED_BY;

DELETE FROM TB0000_SQL_HISTORY WHERE C0000_SCRIPT_NAME = '06-ddl-tb0001_add_audit_fields.sql';