-- Reverte a criptografia dos campos de PII da tabela TB0001_PERSON

-- 1. Remover índices de hash
DROP INDEX IF EXISTS IX0001_EMAIL_HASH;
DROP INDEX IF EXISTS IX0001_NAME_HASH;
DROP INDEX IF EXISTS IX0001_PHONE_HASH;

-- 2. Remover colunas de hash
ALTER TABLE TB0001_PERSON DROP COLUMN IF EXISTS C0001_NAME_HASH;
ALTER TABLE TB0001_PERSON DROP COLUMN IF EXISTS C0001_EMAIL_HASH;
ALTER TABLE TB0001_PERSON DROP COLUMN IF EXISTS C0001_PHONE_HASH;

-- 3. Reverter tipos das colunas criptografadas
ALTER TABLE TB0001_PERSON ALTER COLUMN C0001_NAME TYPE VARCHAR(100);
ALTER TABLE TB0001_PERSON ALTER COLUMN C0001_EMAIL TYPE VARCHAR(255);
ALTER TABLE TB0001_PERSON ALTER COLUMN C0001_PHONE TYPE VARCHAR(20);

-- 4. Recriar constraints removidas
ALTER TABLE TB0001_PERSON ADD CONSTRAINT chk_name_length CHECK (LENGTH(TRIM(C0001_NAME)) >= 3);
ALTER TABLE TB0001_PERSON ADD CONSTRAINT chk_email_length CHECK (LENGTH(TRIM(C0001_EMAIL)) >= 5);

-- 5. Recriar índice original de email
CREATE UNIQUE INDEX IX0001_EMAIL_LOWER ON TB0001_PERSON (LOWER(C0001_EMAIL));

-- 6. Restaurar comentários originais
COMMENT ON COLUMN TB0001_PERSON.C0001_NAME IS 'Nome completo da pessoa';
COMMENT ON COLUMN TB0001_PERSON.C0001_EMAIL IS 'Endereço de email da pessoa';
COMMENT ON COLUMN TB0001_PERSON.C0001_PHONE IS 'Telefone da pessoa (formato brasileiro)';
