-- ATENÇÃO: Este script reverte as alterações em ordem inversa

-- Revogar Permissões
REVOKE ALL ON TB0005_COMPANY FROM "TIME-TRACKER-API";
REVOKE ALL ON SEQUENCE seq_tb0005_company FROM "TIME-TRACKER-API";

-- Remover Índices
DROP INDEX IF EXISTS IX0005_SQ_ID;
DROP INDEX IF EXISTS IX0005_NAME;
DROP INDEX IF EXISTS IX0005_ACTIVE;
DROP INDEX IF EXISTS IX0005_CREATED_BY;
DROP INDEX IF EXISTS IX0005_CREATED_AT;

-- Remover Tabela
DROP TABLE IF EXISTS TB0005_COMPANY CASCADE;

-- Remover Sequence
DROP SEQUENCE IF EXISTS seq_tb0005_company;

-- Remover registro do histórico
DELETE FROM TB0000_SQL_HISTORY WHERE C0000_SCRIPT_NAME = '09-ddl-tb0005_company.sql';
