-- ATENÇÃO: Este script reverte as alterações em ordem inversa

-- Revogar Permissões
REVOKE ALL ON TB0006_TEAM FROM "TIME-TRACKER-API";
REVOKE ALL ON SEQUENCE seq_tb0006_team FROM "TIME-TRACKER-API";

-- Remover Índices
DROP INDEX IF EXISTS IX0006_SQ_ID;
DROP INDEX IF EXISTS IX0006_COMPANY_ID;
DROP INDEX IF EXISTS IX0006_NAME;
DROP INDEX IF EXISTS IX0006_ACTIVE;
DROP INDEX IF EXISTS IX0006_CREATED_BY;
DROP INDEX IF EXISTS IX0006_CREATED_AT;
DROP INDEX IF EXISTS IX0006_COMPANY_NAME;

-- Remover Tabela
DROP TABLE IF EXISTS TB0006_TEAM CASCADE;

-- Remover Sequence
DROP SEQUENCE IF EXISTS seq_tb0006_team;

-- Remover registro do histórico
DELETE FROM TB0000_SQL_HISTORY WHERE C0000_SCRIPT_NAME = '10-ddl-tb0006_team.sql';
