-- ATENÇÃO: Este script reverte as alterações em ordem inversa

-- Revogar Permissões
REVOKE ALL ON TB0007_PROJECT FROM "TIME-TRACKER-API";
REVOKE ALL ON SEQUENCE seq_tb0007_project FROM "TIME-TRACKER-API";

-- Remover Índices
DROP INDEX IF EXISTS IX0007_SQ_ID;
DROP INDEX IF EXISTS IX0007_COMPANY_ID;
DROP INDEX IF EXISTS IX0007_TEAM_ID;
DROP INDEX IF EXISTS IX0007_NAME;
DROP INDEX IF EXISTS IX0007_STATUS;
DROP INDEX IF EXISTS IX0007_ACTIVE;
DROP INDEX IF EXISTS IX0007_CREATED_BY;
DROP INDEX IF EXISTS IX0007_CREATED_AT;
DROP INDEX IF EXISTS IX0007_COMPANY_STATUS;
DROP INDEX IF EXISTS IX0007_TEAM_STATUS;

-- Remover Tabela
DROP TABLE IF EXISTS TB0007_PROJECT CASCADE;

-- Remover Sequence
DROP SEQUENCE IF EXISTS seq_tb0007_project;

-- Remover registro do histórico
DELETE FROM TB0000_SQL_HISTORY WHERE C0000_SCRIPT_NAME = '11-ddl-tb0007_project.sql';
