-- ATENÇÃO: Este script reverte as alterações em ordem inversa

-- Revogar Permissões
REVOKE ALL ON TB0010_USER_TEAM FROM "TIME-TRACKER-API";
REVOKE ALL ON SEQUENCE seq_tb0010_user_team FROM "TIME-TRACKER-API";

-- Remover Índices
DROP INDEX IF EXISTS IX0010_SQ_ID;
DROP INDEX IF EXISTS IX0010_USER_ID;
DROP INDEX IF EXISTS IX0010_TEAM_ID;
DROP INDEX IF EXISTS IX0010_ROLE;
DROP INDEX IF EXISTS IX0010_APPROVED;
DROP INDEX IF EXISTS IX0010_ACTIVE;
DROP INDEX IF EXISTS IX0010_CREATED_BY;
DROP INDEX IF EXISTS IX0010_CREATED_AT;
DROP INDEX IF EXISTS IX0010_USER_TEAM_UNIQUE;
DROP INDEX IF EXISTS IX0010_USER_TEAM_APPROVED;

-- Remover Tabela
DROP TABLE IF EXISTS TB0010_USER_TEAM CASCADE;

-- Remover Sequence
DROP SEQUENCE IF EXISTS seq_tb0010_user_team;

-- Remover registro do histórico
DELETE FROM TB0000_SQL_HISTORY WHERE C0000_SCRIPT_NAME = '14-ddl-tb0010_user_team.sql';
