apiVersion: v1
kind: Secret
metadata:
  name: time-tracker-api-secret
  namespace: time-tracker
type: Opaque
stringData:
  DB_PASSWORD: "set_me"
  REDIS_PASSWORD: "set_me"
  APP_ENCRYPTION_KEY: "set_me"
  JWT_SECRET: "set_me"
  HEALTH_APP_KEY: "set_me"
  SMTP_PASSWORD: "set_me"
  APP_FRONTEND_URL: "set_me"
