name: time-tracker-api-dev

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: time-tracker-api-dev
    ports:
      - "8080:8080"
    env_file: .env.dev
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - JAVA_OPTS=-Xms256m -Xmx512m
    deploy:
      resources:
        limits:
          memory: 1g
