-- Script de criação da tabela de histórico de execução de scripts SQL
-- Este deve ser o primeiro script a ser executado no banco de dados

CREATE TABLE TB0000_SQL_HISTORY (
    C0000_HISTORY_ID SERIAL PRIMARY KEY,
    C0000_SCRIPT_NAME VARCHAR(255) NOT NULL UNIQUE,
    C0000_EXECUTED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX IX0000_EXECUTED_AT ON TB0000_SQL_HISTORY (C0000_EXECUTED_AT DESC);
CREATE INDEX IX0000_SCRIPT_NAME ON TB0000_SQL_HISTORY (C0000_SCRIPT_NAME);

COMMENT ON TABLE TB0000_SQL_HISTORY IS 'Tabela de controle de execução de scripts SQL';
COMMENT ON COLUMN TB0000_SQL_HISTORY.C0000_HISTORY_ID IS 'Identificador único do registro';
COMMENT ON COLUMN TB0000_SQL_HISTORY.C0000_SCRIPT_NAME IS 'Nome do arquivo do script executado';
COMMENT ON COLUMN TB0000_SQL_HISTORY.C0000_EXECUTED_AT IS 'Data e hora da execução do script';

GRANT SELECT, INSERT, DELETE ON TB0000_SQL_HISTORY TO "TIME-TRACKER-API";
GRANT USAGE, SELECT ON SEQUENCE tb0000_sql_history_c0000_history_id_seq TO "TIME-TRACKER-API";

-- Registrar a execução deste próprio script
INSERT INTO TB0000_SQL_HISTORY (C0000_SCRIPT_NAME) VALUES ('00_ddl_tb0000_sql_history.sql');
