DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM TB0000_SQL_HISTORY WHERE C0000_SCRIPT_NAME = '01-ddl-tb0001_person.sql') THEN
        RAISE EXCEPTION 'Script 01-ddl-tb0001_person.sql não foi executado. Não há nada para reverter.';
    END IF;
END $$;

REVOKE ALL ON TB0001_PERSON FROM "TIME-TRACKER-API";
REVOKE ALL ON SEQUENCE seq_TB0001_PERSON FROM "TIME-TRACKER-API";

DROP INDEX IF EXISTS IX0001_SQ_ID;
DROP INDEX IF EXISTS IX0001_EMAIL_LOWER;
DROP INDEX IF EXISTS IX0001_CREATED_AT;
DROP INDEX IF EXISTS IX0001_ACTIVE;

DROP TABLE IF EXISTS TB0001_PERSON CASCADE;

DROP SEQUENCE IF EXISTS seq_TB0001_PERSON;

-- Remover o registro de execução do histórico
DELETE FROM TB0000_SQL_HISTORY WHERE C0000_SCRIPT_NAME = '01-ddl-tb0001_person.sql';
