CREATE SEQUENCE seq_TB0002_USER_AUTH START 1;

CREATE TABLE TB0002_USER_AUTH (
    C0002_USER_ID UUID PRIMARY KEY, -- UserID in Auth does not auto-generate, instead uses the same ID of the respective UserData
    C0002_USERNAME VARCHAR(100) NOT NULL,
    C0002_PASSWORD_HASH VARCHAR(512) NOT NULL,
    C0002_PASSWORD_SALT VARCHAR(512) NOT NULL,
    C0002_ACCESS_TOKEN VARCHAR(512),
    C0002_CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    C0002_UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    C0002_ACTIVE BOOLEAN DEFAULT TRUE NOT NULL,
    C0002_FAILED_ATTEMPTS INT DEFAULT 0 NOT NULL,
    C0002_LAST_PASSWORD_CHANGE TIMESTAMP WITH TIME ZONE,
    C0002_PASSWORD_RESET_REQUESTED BOOLEAN DEFAULT FALSE NOT NULL,
    C0002_LAST_PASSWORD_RESET_REQUEST TIMESTAMP WITH TIME ZONE,
    C0002_LAST_LOGIN TIMESTAMP WITH TIME ZONE,
    C0002_SQ_ID INT NOT NULL DEFAULT nextval('seq_TB0002_USER_AUTH'),
    CONSTRAINT chk_username_length CHECK (LENGTH(TRIM(C0002_USERNAME)) >= 3),
    CONSTRAINT chk_failed_attempts CHECK (C0002_FAILED_ATTEMPTS >= 0),
    CONSTRAINT fk_user_id FOREIGN KEY (C0002_USER_ID) REFERENCES TB0001_PERSON(C0001_ID)
);

CREATE UNIQUE INDEX IX0002_USERNAME_LOWER ON TB0002_USER_AUTH (LOWER(C0002_USERNAME));
CREATE UNIQUE INDEX IX0002_SQ_ID ON TB0002_USER_AUTH (C0002_SQ_ID);
CREATE INDEX IX0002_ACTIVE ON TB0002_USER_AUTH (C0002_ACTIVE) WHERE C0002_ACTIVE = TRUE;
CREATE INDEX IX0002_CREATED_AT ON TB0002_USER_AUTH (C0002_CREATED_AT DESC);

COMMENT ON TABLE TB0002_USER_AUTH IS 'Tabela de autenticação de usuários';
COMMENT ON COLUMN TB0002_USER_AUTH.C0002_USER_ID IS 'Identificador único do usuário, compartilhado com TB0001 obrigatoriamente, definido a nível de aplicação';
COMMENT ON COLUMN TB0002_USER_AUTH.C0002_USERNAME IS 'Nome de usuário';
COMMENT ON COLUMN TB0002_USER_AUTH.C0002_PASSWORD_HASH IS 'Hash da senha criptografada';
COMMENT ON COLUMN TB0002_USER_AUTH.C0002_PASSWORD_SALT IS 'Salt utilizado na criptografia da senha';
COMMENT ON COLUMN TB0002_USER_AUTH.C0002_ACCESS_TOKEN IS 'Token de primeiro acesso ou recuperação de senha';
COMMENT ON COLUMN TB0002_USER_AUTH.C0002_LAST_PASSWORD_CHANGE IS 'Data e hora da última alteração de senha';
COMMENT ON COLUMN TB0002_USER_AUTH.C0002_PASSWORD_RESET_REQUESTED IS 'Indica se há uma solicitação de redefinição de senha pendente';
COMMENT ON COLUMN TB0002_USER_AUTH.C0002_LAST_PASSWORD_RESET_REQUEST IS 'Data e hora da última solicitação de redefinição de senha';
COMMENT ON COLUMN TB0002_USER_AUTH.C0002_SQ_ID IS 'ID sequencial numérico';
COMMENT ON COLUMN TB0002_USER_AUTH.C0002_FAILED_ATTEMPTS IS 'Contador de tentativas de login falhadas';

GRANT SELECT, INSERT, UPDATE, DELETE ON TB0002_USER_AUTH TO "TIME-TRACKER-API";
GRANT USAGE, SELECT ON SEQUENCE seq_TB0002_USER_AUTH TO "TIME-TRACKER-API";

-- Registrar a execução deste script
INSERT INTO TB0000_SQL_HISTORY (C0000_SCRIPT_NAME) VALUES ('02-ddl-tb0002_user_auth.sql');