CREATE SEQUENCE seq_tb0003_failed_email START 1;

CREATE TABLE TB0003_FAILED_EMAIL (
    C0003_FAILED_EMAIL_ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    C0003_RECIPIENT VARCHAR(255) NOT NULL,
    C0003_SUBJECT VARCHAR(500) NOT NULL,
    C0003_TEMPLATE_NAME VARCHAR(100) NOT NULL,
    C0003_TEMPLATE_DATA TEXT NOT NULL,
    C0003_LOCALE VARCHAR(10) NOT NULL,
    C0003_ERROR_MESSAGE TEXT,
    C0003_STACK_TRACE TEXT,
    C0003_RETRY_COUNT INT DEFAULT 0 NOT NULL,
    C0003_CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    C0003_UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    C0003_SQ_ID INT NOT NULL DEFAULT nextval('seq_tb0003_failed_email'),
    CONSTRAINT chk_retry_count CHECK (C0003_RETRY_COUNT >= 0)
);

CREATE UNIQUE INDEX IX0003_SQ_ID ON TB0003_FAILED_EMAIL (C0003_SQ_ID);
CREATE INDEX IX0003_CREATED_AT ON TB0003_FAILED_EMAIL (C0003_CREATED_AT DESC);
CREATE INDEX IX0003_RECIPIENT ON TB0003_FAILED_EMAIL (C0003_RECIPIENT);
CREATE INDEX IX0003_RETRY_COUNT ON TB0003_FAILED_EMAIL (C0003_RETRY_COUNT);

COMMENT ON TABLE TB0003_FAILED_EMAIL IS 'Tabela de emails que falharam no envio';
COMMENT ON COLUMN TB0003_FAILED_EMAIL.C0003_FAILED_EMAIL_ID IS 'Identificador único do email falhado';
COMMENT ON COLUMN TB0003_FAILED_EMAIL.C0003_RECIPIENT IS 'Endereço de email do destinatário';
COMMENT ON COLUMN TB0003_FAILED_EMAIL.C0003_SUBJECT IS 'Assunto do email';
COMMENT ON COLUMN TB0003_FAILED_EMAIL.C0003_TEMPLATE_NAME IS 'Nome do template usado para gerar o email';
COMMENT ON COLUMN TB0003_FAILED_EMAIL.C0003_TEMPLATE_DATA IS 'Dados do template em JSON para recriar o email';
COMMENT ON COLUMN TB0003_FAILED_EMAIL.C0003_LOCALE IS 'Locale do email (pt-BR, en, etc)';
COMMENT ON COLUMN TB0003_FAILED_EMAIL.C0003_ERROR_MESSAGE IS 'Mensagem de erro da última tentativa';
COMMENT ON COLUMN TB0003_FAILED_EMAIL.C0003_STACK_TRACE IS 'Stack trace do erro';
COMMENT ON COLUMN TB0003_FAILED_EMAIL.C0003_RETRY_COUNT IS 'Número de tentativas de reenvio realizadas';
COMMENT ON COLUMN TB0003_FAILED_EMAIL.C0003_SQ_ID IS 'ID sequencial numérico';

GRANT SELECT, INSERT, UPDATE, DELETE ON TB0003_FAILED_EMAIL TO "TIME-TRACKER-API";
GRANT USAGE, SELECT ON SEQUENCE seq_tb0003_failed_email TO "TIME-TRACKER-API";

-- Registrar a execução deste script
INSERT INTO TB0000_SQL_HISTORY (C0000_SCRIPT_NAME) VALUES ('03-ddl-tb0003_failed_email.sql');
