ALTER TABLE TB0002_USER_AUTH 
ADD COLUMN C0002_USER_CONFIRMED BOOLEAN DEFAULT FALSE NOT NULL;

COMMENT ON COLUMN TB0002_USER_AUTH.C0002_USER_CONFIRMED IS 'Indica se o usuário confirmou o cadastro via email';

INSERT INTO TB0000_SQL_HISTORY (C0000_SCRIPT_NAME) VALUES ('04-ddl-tb0002_add_user_confirmed.sql');
