-- Criar Sequence
CREATE SEQUENCE seq_tb0008_time_entry START 1;

-- Criar Tabela (FLEXÍVEL - permite uso pessoal e corporativo)
CREATE TABLE TB0008_TIME_ENTRY (
    C0008_ENTRY_ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    C0008_USER_ID UUID NOT NULL,
    C0008_COMPANY_ID UUID,  -- OPCIONAL (NULL = uso pessoal sem empresa)
    C0008_TEAM_ID UUID,     -- OPCIONAL (NULL = sem time)
    C0008_PROJECT_ID UUID,  -- OPCIONAL (NULL = sem projeto)
    C0008_DESCRIPTION TEXT,
    C0008_TAGS VARCHAR(500),
    C0008_START_TIME TIMESTAMP WITH TIME ZONE NOT NULL,
    C0008_END_TIME TIMESTAMP WITH TIME ZONE,
    C0008_DURATION_SECONDS BIGINT,
    C0008_STATUS VARCHAR(20) DEFAULT 'ACTIVE' NOT NULL,
    C0008_ACTIVE BOOLEAN DEFAULT TRUE NOT NULL,
    C0008_CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    C0008_UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    C0008_CREATED_BY UUID NOT NULL,
    C0008_UPDATED_BY UUID NOT NULL,
    C0008_SQ_ID INT NOT NULL DEFAULT nextval('seq_tb0008_time_entry'),
    CONSTRAINT chk_entry_status CHECK (C0008_STATUS IN ('ACTIVE', 'COMPLETED')),
    CONSTRAINT chk_end_after_start CHECK (C0008_END_TIME IS NULL OR C0008_END_TIME > C0008_START_TIME),
    CONSTRAINT chk_duration_positive CHECK (C0008_DURATION_SECONDS IS NULL OR C0008_DURATION_SECONDS > 0),
    -- Regras de cascata: se tem time, deve ter empresa; se tem projeto, deve ter empresa
    CONSTRAINT chk_team_requires_company CHECK (C0008_TEAM_ID IS NULL OR C0008_COMPANY_ID IS NOT NULL),
    CONSTRAINT chk_project_requires_company CHECK (C0008_PROJECT_ID IS NULL OR C0008_COMPANY_ID IS NOT NULL),
    CONSTRAINT fk_entry_user FOREIGN KEY (C0008_USER_ID) 
        REFERENCES TB0002_USER_AUTH(C0002_USER_ID),
    CONSTRAINT fk_entry_company FOREIGN KEY (C0008_COMPANY_ID) 
        REFERENCES TB0005_COMPANY(C0005_COMPANY_ID),
    CONSTRAINT fk_entry_team FOREIGN KEY (C0008_TEAM_ID) 
        REFERENCES TB0006_TEAM(C0006_TEAM_ID),
    CONSTRAINT fk_entry_project FOREIGN KEY (C0008_PROJECT_ID) 
        REFERENCES TB0007_PROJECT(C0007_PROJECT_ID),
    CONSTRAINT fk_entry_created_by FOREIGN KEY (C0008_CREATED_BY) 
        REFERENCES TB0002_USER_AUTH(C0002_USER_ID),
    CONSTRAINT fk_entry_updated_by FOREIGN KEY (C0008_UPDATED_BY) 
        REFERENCES TB0002_USER_AUTH(C0002_USER_ID)
);

-- Criar Índices
CREATE UNIQUE INDEX IX0008_SQ_ID ON TB0008_TIME_ENTRY (C0008_SQ_ID);
CREATE INDEX IX0008_USER_ID ON TB0008_TIME_ENTRY (C0008_USER_ID);
CREATE INDEX IX0008_COMPANY_ID ON TB0008_TIME_ENTRY (C0008_COMPANY_ID);
CREATE INDEX IX0008_TEAM_ID ON TB0008_TIME_ENTRY (C0008_TEAM_ID);
CREATE INDEX IX0008_PROJECT_ID ON TB0008_TIME_ENTRY (C0008_PROJECT_ID);
CREATE INDEX IX0008_STATUS ON TB0008_TIME_ENTRY (C0008_STATUS);
CREATE INDEX IX0008_ACTIVE ON TB0008_TIME_ENTRY (C0008_ACTIVE) WHERE C0008_ACTIVE = TRUE;
CREATE INDEX IX0008_START_TIME ON TB0008_TIME_ENTRY (C0008_START_TIME DESC);
CREATE INDEX IX0008_CREATED_BY ON TB0008_TIME_ENTRY (C0008_CREATED_BY);
CREATE INDEX IX0008_CREATED_AT ON TB0008_TIME_ENTRY (C0008_CREATED_AT DESC);

-- Índice crítico: garante apenas 1 registro ACTIVE por usuário
CREATE UNIQUE INDEX IX0008_USER_ACTIVE_ENTRY 
ON TB0008_TIME_ENTRY (C0008_USER_ID) 
WHERE C0008_STATUS = 'ACTIVE' AND C0008_ACTIVE = TRUE;

-- Índices compostos para queries comuns
CREATE INDEX IX0008_USER_STATUS_START ON TB0008_TIME_ENTRY (C0008_USER_ID, C0008_STATUS, C0008_START_TIME DESC);
CREATE INDEX IX0008_COMPANY_START ON TB0008_TIME_ENTRY (C0008_COMPANY_ID, C0008_START_TIME DESC);
CREATE INDEX IX0008_TEAM_START ON TB0008_TIME_ENTRY (C0008_TEAM_ID, C0008_START_TIME DESC);
CREATE INDEX IX0008_PROJECT_START ON TB0008_TIME_ENTRY (C0008_PROJECT_ID, C0008_START_TIME DESC);

-- Adicionar Comentários
COMMENT ON TABLE TB0008_TIME_ENTRY IS 'Tabela de registros de tempo (time tracking) - FLEXÍVEL para uso pessoal e corporativo';
COMMENT ON COLUMN TB0008_TIME_ENTRY.C0008_ENTRY_ID IS 'Identificador único do registro de tempo';
COMMENT ON COLUMN TB0008_TIME_ENTRY.C0008_USER_ID IS 'ID do usuário que criou o registro (obrigatório)';
COMMENT ON COLUMN TB0008_TIME_ENTRY.C0008_COMPANY_ID IS 'ID da empresa do registro (OPCIONAL - NULL para uso pessoal)';
COMMENT ON COLUMN TB0008_TIME_ENTRY.C0008_TEAM_ID IS 'ID do time do registro (OPCIONAL - requer empresa se preenchido)';
COMMENT ON COLUMN TB0008_TIME_ENTRY.C0008_PROJECT_ID IS 'ID do projeto (OPCIONAL - requer empresa se preenchido)';
COMMENT ON COLUMN TB0008_TIME_ENTRY.C0008_DESCRIPTION IS 'Descrição da atividade realizada';
COMMENT ON COLUMN TB0008_TIME_ENTRY.C0008_TAGS IS 'Tags separadas por vírgula para categorização';
COMMENT ON COLUMN TB0008_TIME_ENTRY.C0008_START_TIME IS 'Data e hora de início do registro';
COMMENT ON COLUMN TB0008_TIME_ENTRY.C0008_END_TIME IS 'Data e hora de término do registro (NULL se ACTIVE)';
COMMENT ON COLUMN TB0008_TIME_ENTRY.C0008_DURATION_SECONDS IS 'Duração em segundos (calculado ao finalizar)';
COMMENT ON COLUMN TB0008_TIME_ENTRY.C0008_STATUS IS 'Status do registro (ACTIVE ou COMPLETED)';
COMMENT ON COLUMN TB0008_TIME_ENTRY.C0008_ACTIVE IS 'Indica se o registro está ativo (soft delete)';
COMMENT ON COLUMN TB0008_TIME_ENTRY.C0008_CREATED_AT IS 'Data e hora de criação do registro';
COMMENT ON COLUMN TB0008_TIME_ENTRY.C0008_UPDATED_AT IS 'Data e hora da última atualização do registro';
COMMENT ON COLUMN TB0008_TIME_ENTRY.C0008_CREATED_BY IS 'ID do usuário que criou o registro';
COMMENT ON COLUMN TB0008_TIME_ENTRY.C0008_UPDATED_BY IS 'ID do usuário que atualizou o registro pela última vez';
COMMENT ON COLUMN TB0008_TIME_ENTRY.C0008_SQ_ID IS 'ID sequencial numérico';

-- Conceder Permissões
GRANT SELECT, INSERT, UPDATE, DELETE ON TB0008_TIME_ENTRY TO "TIME-TRACKER-API";
GRANT USAGE, SELECT ON SEQUENCE seq_tb0008_time_entry TO "TIME-TRACKER-API";

-- Registrar a execução deste script
INSERT INTO TB0000_SQL_HISTORY (C0000_SCRIPT_NAME) VALUES ('12-ddl-tb0008_time_entry.sql');
