-- ATENÇÃO: Este script reverte as alterações em ordem inversa

-- Revogar Permissões
REVOKE ALL ON TB0008_TIME_ENTRY FROM "TIME-TRACKER-API";
REVOKE ALL ON SEQUENCE seq_tb0008_time_entry FROM "TIME-TRACKER-API";

-- Remover Índices
DROP INDEX IF EXISTS IX0008_SQ_ID;
DROP INDEX IF EXISTS IX0008_USER_ID;
DROP INDEX IF EXISTS IX0008_COMPANY_ID;
DROP INDEX IF EXISTS IX0008_TEAM_ID;
DROP INDEX IF EXISTS IX0008_PROJECT_ID;
DROP INDEX IF EXISTS IX0008_STATUS;
DROP INDEX IF EXISTS IX0008_ACTIVE;
DROP INDEX IF EXISTS IX0008_START_TIME;
DROP INDEX IF EXISTS IX0008_CREATED_BY;
DROP INDEX IF EXISTS IX0008_CREATED_AT;
DROP INDEX IF EXISTS IX0008_USER_ACTIVE_ENTRY;
DROP INDEX IF EXISTS IX0008_USER_STATUS_START;
DROP INDEX IF EXISTS IX0008_COMPANY_START;
DROP INDEX IF EXISTS IX0008_TEAM_START;
DROP INDEX IF EXISTS IX0008_PROJECT_START;

-- Remover Tabela
DROP TABLE IF EXISTS TB0008_TIME_ENTRY CASCADE;

-- Remover Sequence
DROP SEQUENCE IF EXISTS seq_tb0008_time_entry;

-- Remover registro do histórico
DELETE FROM TB0000_SQL_HISTORY WHERE C0000_SCRIPT_NAME = '12-ddl-tb0008_time_entry.sql';
