-- ATENÇÃO: Este script reverte as alterações em ordem inversa

-- Revogar Permissões
REVOKE ALL ON TB0009_USER_COMPANY FROM "TIME-TRACKER-API";
REVOKE ALL ON SEQUENCE seq_tb0009_user_company FROM "TIME-TRACKER-API";

-- Remover Índices
DROP INDEX IF EXISTS IX0009_SQ_ID;
DROP INDEX IF EXISTS IX0009_USER_ID;
DROP INDEX IF EXISTS IX0009_COMPANY_ID;
DROP INDEX IF EXISTS IX0009_ROLE;
DROP INDEX IF EXISTS IX0009_APPROVED;
DROP INDEX IF EXISTS IX0009_ACTIVE;
DROP INDEX IF EXISTS IX0009_CREATED_BY;
DROP INDEX IF EXISTS IX0009_CREATED_AT;
DROP INDEX IF EXISTS IX0009_USER_COMPANY_UNIQUE;
DROP INDEX IF EXISTS IX0009_USER_COMPANY_APPROVED;

-- Remover Tabela
DROP TABLE IF EXISTS TB0009_USER_COMPANY CASCADE;

-- Remover Sequence
DROP SEQUENCE IF EXISTS seq_tb0009_user_company;

-- Remover registro do histórico
DELETE FROM TB0000_SQL_HISTORY WHERE C0000_SCRIPT_NAME = '13-ddl-tb0009_user_company.sql';
