-- Criar Sequence
CREATE SEQUENCE seq_tb0009_user_company START 1;

-- Criar Tabela
CREATE TABLE TB0009_USER_COMPANY (
    C0009_ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    C0009_USER_ID UUID NOT NULL,
    C0009_COMPANY_ID UUID NOT NULL,
    C0009_ROLE VARCHAR(50) DEFAULT 'MEMBER' NOT NULL,
    C0009_APPROVED BOOLEAN DEFAULT FALSE NOT NULL,
    C0009_ACTIVE BOOLEAN DEFAULT TRUE NOT NULL,
    C0009_CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    C0009_UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    C0009_CREATED_BY UUID NOT NULL,
    C0009_UPDATED_BY UUID NOT NULL,
    C0009_SQ_ID INT NOT NULL DEFAULT nextval('seq_tb0009_user_company'),
    CONSTRAINT chk_user_company_role CHECK (C0009_ROLE IN ('OWNER', 'MANAGER', 'MEMBER')),
    CONSTRAINT fk_user_company_user FOREIGN KEY (C0009_USER_ID) 
        REFERENCES TB0002_USER_AUTH(C0002_USER_ID) ON DELETE CASCADE,
    CONSTRAINT fk_user_company_company FOREIGN KEY (C0009_COMPANY_ID) 
        REFERENCES TB0005_COMPANY(C0005_COMPANY_ID) ON DELETE CASCADE,
    CONSTRAINT fk_user_company_created_by FOREIGN KEY (C0009_CREATED_BY) 
        REFERENCES TB0002_USER_AUTH(C0002_USER_ID),
    CONSTRAINT fk_user_company_updated_by FOREIGN KEY (C0009_UPDATED_BY) 
        REFERENCES TB0002_USER_AUTH(C0002_USER_ID)
);

-- Criar Índices
CREATE UNIQUE INDEX IX0009_SQ_ID ON TB0009_USER_COMPANY (C0009_SQ_ID);
CREATE INDEX IX0009_USER_ID ON TB0009_USER_COMPANY (C0009_USER_ID);
CREATE INDEX IX0009_COMPANY_ID ON TB0009_USER_COMPANY (C0009_COMPANY_ID);
CREATE INDEX IX0009_ROLE ON TB0009_USER_COMPANY (C0009_ROLE);
CREATE INDEX IX0009_APPROVED ON TB0009_USER_COMPANY (C0009_APPROVED);
CREATE INDEX IX0009_ACTIVE ON TB0009_USER_COMPANY (C0009_ACTIVE) WHERE C0009_ACTIVE = TRUE;
CREATE INDEX IX0009_CREATED_BY ON TB0009_USER_COMPANY (C0009_CREATED_BY);
CREATE INDEX IX0009_CREATED_AT ON TB0009_USER_COMPANY (C0009_CREATED_AT DESC);

-- Índice único: um usuário não pode ter múltiplos vínculos ativos com a mesma empresa
CREATE UNIQUE INDEX IX0009_USER_COMPANY_UNIQUE 
ON TB0009_USER_COMPANY (C0009_USER_ID, C0009_COMPANY_ID) 
WHERE C0009_ACTIVE = TRUE;

-- Índice para buscar vínculos aprovados
CREATE INDEX IX0009_USER_COMPANY_APPROVED 
ON TB0009_USER_COMPANY (C0009_USER_ID, C0009_COMPANY_ID, C0009_APPROVED) 
WHERE C0009_ACTIVE = TRUE AND C0009_APPROVED = TRUE;

-- Adicionar Comentários
COMMENT ON TABLE TB0009_USER_COMPANY IS 'Tabela de relacionamento entre usuários e empresas';
COMMENT ON COLUMN TB0009_USER_COMPANY.C0009_ID IS 'Identificador único do relacionamento';
COMMENT ON COLUMN TB0009_USER_COMPANY.C0009_USER_ID IS 'ID do usuário';
COMMENT ON COLUMN TB0009_USER_COMPANY.C0009_COMPANY_ID IS 'ID da empresa';
COMMENT ON COLUMN TB0009_USER_COMPANY.C0009_ROLE IS 'Papel do usuário na empresa (OWNER, MANAGER, MEMBER)';
COMMENT ON COLUMN TB0009_USER_COMPANY.C0009_APPROVED IS 'Indica se o vínculo foi aprovado (OWNER auto-aprovado, outros precisam aprovação)';
COMMENT ON COLUMN TB0009_USER_COMPANY.C0009_ACTIVE IS 'Indica se o relacionamento está ativo';
COMMENT ON COLUMN TB0009_USER_COMPANY.C0009_CREATED_AT IS 'Data e hora de criação do registro';
COMMENT ON COLUMN TB0009_USER_COMPANY.C0009_UPDATED_AT IS 'Data e hora da última atualização do registro';
COMMENT ON COLUMN TB0009_USER_COMPANY.C0009_CREATED_BY IS 'ID do usuário que criou o registro';
COMMENT ON COLUMN TB0009_USER_COMPANY.C0009_UPDATED_BY IS 'ID do usuário que atualizou o registro pela última vez';
COMMENT ON COLUMN TB0009_USER_COMPANY.C0009_SQ_ID IS 'ID sequencial numérico';

-- Conceder Permissões
GRANT SELECT, INSERT, UPDATE, DELETE ON TB0009_USER_COMPANY TO "TIME-TRACKER-API";
GRANT USAGE, SELECT ON SEQUENCE seq_tb0009_user_company TO "TIME-TRACKER-API";

-- Registrar a execução deste script
INSERT INTO TB0000_SQL_HISTORY (C0000_SCRIPT_NAME) VALUES ('16-ddl-tb0009_user_company.sql');
