-- Criar Sequence
CREATE SEQUENCE seq_tb0011_project_team START 1;

-- Criar Tabela (relacionamento N:N entre projetos e times)
CREATE TABLE TB0011_PROJECT_TEAM (
    C0011_ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    C0011_PROJECT_ID UUID NOT NULL,
    C0011_TEAM_ID UUID NOT NULL,
    C0011_ACTIVE BOOLEAN DEFAULT TRUE NOT NULL,
    C0011_CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    C0011_UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    C0011_CREATED_BY UUID NOT NULL,
    C0011_UPDATED_BY UUID NOT NULL,
    C0011_SQ_ID INT NOT NULL DEFAULT nextval('seq_tb0011_project_team'),
    CONSTRAINT fk_project_team_project FOREIGN KEY (C0011_PROJECT_ID)
        REFERENCES TB0007_PROJECT(C0007_PROJECT_ID) ON DELETE CASCADE,
    CONSTRAINT fk_project_team_team FOREIGN KEY (C0011_TEAM_ID)
        REFERENCES TB0006_TEAM(C0006_TEAM_ID) ON DELETE CASCADE,
    CONSTRAINT fk_project_team_created_by FOREIGN KEY (C0011_CREATED_BY)
        REFERENCES TB0002_USER_AUTH(C0002_USER_ID),
    CONSTRAINT fk_project_team_updated_by FOREIGN KEY (C0011_UPDATED_BY)
        REFERENCES TB0002_USER_AUTH(C0002_USER_ID)
);

-- Criar Índices
CREATE UNIQUE INDEX IX0011_SQ_ID ON TB0011_PROJECT_TEAM (C0011_SQ_ID);
CREATE INDEX IX0011_PROJECT_ID ON TB0011_PROJECT_TEAM (C0011_PROJECT_ID);
CREATE INDEX IX0011_TEAM_ID ON TB0011_PROJECT_TEAM (C0011_TEAM_ID);
CREATE INDEX IX0011_ACTIVE ON TB0011_PROJECT_TEAM (C0011_ACTIVE) WHERE C0011_ACTIVE = TRUE;
CREATE INDEX IX0011_CREATED_BY ON TB0011_PROJECT_TEAM (C0011_CREATED_BY);
CREATE INDEX IX0011_CREATED_AT ON TB0011_PROJECT_TEAM (C0011_CREATED_AT DESC);

-- Índice único: um projeto não pode ter múltiplos vínculos ativos com o mesmo time
CREATE UNIQUE INDEX IX0011_PROJECT_TEAM_UNIQUE
ON TB0011_PROJECT_TEAM (C0011_PROJECT_ID, C0011_TEAM_ID)
WHERE C0011_ACTIVE = TRUE;

-- Adicionar Comentários
COMMENT ON TABLE TB0011_PROJECT_TEAM IS 'Tabela de relacionamento N:N entre projetos e times';
COMMENT ON COLUMN TB0011_PROJECT_TEAM.C0011_ID IS 'Identificador único do relacionamento';
COMMENT ON COLUMN TB0011_PROJECT_TEAM.C0011_PROJECT_ID IS 'ID do projeto';
COMMENT ON COLUMN TB0011_PROJECT_TEAM.C0011_TEAM_ID IS 'ID do time';
COMMENT ON COLUMN TB0011_PROJECT_TEAM.C0011_ACTIVE IS 'Indica se o relacionamento está ativo';
COMMENT ON COLUMN TB0011_PROJECT_TEAM.C0011_CREATED_AT IS 'Data e hora de criação do registro';
COMMENT ON COLUMN TB0011_PROJECT_TEAM.C0011_UPDATED_AT IS 'Data e hora da última atualização do registro';
COMMENT ON COLUMN TB0011_PROJECT_TEAM.C0011_CREATED_BY IS 'ID do usuário que criou o registro';
COMMENT ON COLUMN TB0011_PROJECT_TEAM.C0011_UPDATED_BY IS 'ID do usuário que atualizou o registro pela última vez';
COMMENT ON COLUMN TB0011_PROJECT_TEAM.C0011_SQ_ID IS 'ID sequencial numérico';

-- Conceder Permissões
GRANT SELECT, INSERT, UPDATE, DELETE ON TB0011_PROJECT_TEAM TO "TIME-TRACKER-API";
GRANT USAGE, SELECT ON SEQUENCE seq_tb0011_project_team TO "TIME-TRACKER-API";
