-- Criar Sequence
CREATE SEQUENCE seq_tb0012_user_project START 1;

-- Criar Tabela (atribuição de projeto a membro, sempre via um time)
CREATE TABLE TB0012_USER_PROJECT (
    C0012_ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    C0012_USER_ID UUID NOT NULL,
    C0012_PROJECT_ID UUID NOT NULL,
    C0012_TEAM_ID UUID NOT NULL,
    C0012_ACTIVE BOOLEAN DEFAULT TRUE NOT NULL,
    C0012_CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    C0012_UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    C0012_CREATED_BY UUID NOT NULL,
    C0012_UPDATED_BY UUID NOT NULL,
    C0012_SQ_ID INT NOT NULL DEFAULT nextval('seq_tb0012_user_project'),
    CONSTRAINT fk_user_project_user FOREIGN KEY (C0012_USER_ID)
        REFERENCES TB0002_USER_AUTH(C0002_USER_ID) ON DELETE CASCADE,
    CONSTRAINT fk_user_project_project FOREIGN KEY (C0012_PROJECT_ID)
        REFERENCES TB0007_PROJECT(C0007_PROJECT_ID) ON DELETE CASCADE,
    CONSTRAINT fk_user_project_team FOREIGN KEY (C0012_TEAM_ID)
        REFERENCES TB0006_TEAM(C0006_TEAM_ID) ON DELETE CASCADE,
    CONSTRAINT fk_user_project_created_by FOREIGN KEY (C0012_CREATED_BY)
        REFERENCES TB0002_USER_AUTH(C0002_USER_ID),
    CONSTRAINT fk_user_project_updated_by FOREIGN KEY (C0012_UPDATED_BY)
        REFERENCES TB0002_USER_AUTH(C0002_USER_ID)
);

-- Criar Índices
CREATE UNIQUE INDEX IX0012_SQ_ID ON TB0012_USER_PROJECT (C0012_SQ_ID);
CREATE INDEX IX0012_USER_ID ON TB0012_USER_PROJECT (C0012_USER_ID);
CREATE INDEX IX0012_PROJECT_ID ON TB0012_USER_PROJECT (C0012_PROJECT_ID);
CREATE INDEX IX0012_TEAM_ID ON TB0012_USER_PROJECT (C0012_TEAM_ID);
CREATE INDEX IX0012_ACTIVE ON TB0012_USER_PROJECT (C0012_ACTIVE) WHERE C0012_ACTIVE = TRUE;
CREATE INDEX IX0012_CREATED_BY ON TB0012_USER_PROJECT (C0012_CREATED_BY);
CREATE INDEX IX0012_CREATED_AT ON TB0012_USER_PROJECT (C0012_CREATED_AT DESC);

-- Índice único: um usuário não pode ter múltiplas atribuições ativas
-- do mesmo projeto via o mesmo time
CREATE UNIQUE INDEX IX0012_USER_PROJECT_TEAM_UNIQUE
ON TB0012_USER_PROJECT (C0012_USER_ID, C0012_PROJECT_ID, C0012_TEAM_ID)
WHERE C0012_ACTIVE = TRUE;

-- Adicionar Comentários
COMMENT ON TABLE TB0012_USER_PROJECT IS 'Tabela de atribuição de projetos a membros de times';
COMMENT ON COLUMN TB0012_USER_PROJECT.C0012_ID IS 'Identificador único da atribuição';
COMMENT ON COLUMN TB0012_USER_PROJECT.C0012_USER_ID IS 'ID do usuário atribuído';
COMMENT ON COLUMN TB0012_USER_PROJECT.C0012_PROJECT_ID IS 'ID do projeto atribuído';
COMMENT ON COLUMN TB0012_USER_PROJECT.C0012_TEAM_ID IS 'ID do time através do qual o projeto foi atribuído';
COMMENT ON COLUMN TB0012_USER_PROJECT.C0012_ACTIVE IS 'Indica se a atribuição está ativa';
COMMENT ON COLUMN TB0012_USER_PROJECT.C0012_CREATED_AT IS 'Data e hora de criação do registro';
COMMENT ON COLUMN TB0012_USER_PROJECT.C0012_UPDATED_AT IS 'Data e hora da última atualização do registro';
COMMENT ON COLUMN TB0012_USER_PROJECT.C0012_CREATED_BY IS 'ID do usuário que criou o registro';
COMMENT ON COLUMN TB0012_USER_PROJECT.C0012_UPDATED_BY IS 'ID do usuário que atualizou o registro pela última vez';
COMMENT ON COLUMN TB0012_USER_PROJECT.C0012_SQ_ID IS 'ID sequencial numérico';

-- Conceder Permissões
GRANT SELECT, INSERT, UPDATE, DELETE ON TB0012_USER_PROJECT TO "TIME-TRACKER-API";
GRANT USAGE, SELECT ON SEQUENCE seq_tb0012_user_project TO "TIME-TRACKER-API";
