-- Afiliação do usuário à plataforma:
-- PENDING (não respondeu o onboarding), INDEPENDENT (sem vínculo), COMPANY (vinculado a empresa)
ALTER TABLE TB0002_USER_AUTH
ADD COLUMN C0002_AFFILIATION VARCHAR(20) DEFAULT 'PENDING' NOT NULL,
ADD CONSTRAINT chk_affiliation CHECK (C0002_AFFILIATION IN ('PENDING', 'INDEPENDENT', 'COMPANY'));

CREATE INDEX IX0002_AFFILIATION ON TB0002_USER_AUTH (C0002_AFFILIATION);

COMMENT ON COLUMN TB0002_USER_AUTH.C0002_AFFILIATION IS 'Status de afiliação do usuário: PENDING, INDEPENDENT ou COMPANY';
