-- Projetos pessoais: COMPANY_ID vira opcional e USER_ID identifica o dono
ALTER TABLE TB0007_PROJECT ALTER COLUMN C0007_COMPANY_ID DROP NOT NULL;
ALTER TABLE TB0007_PROJECT ADD COLUMN C0007_USER_ID UUID;

ALTER TABLE TB0007_PROJECT
ADD CONSTRAINT fk_project_user FOREIGN KEY (C0007_USER_ID)
    REFERENCES TB0002_USER_AUTH(C0002_USER_ID) ON DELETE CASCADE;

-- Todo projeto pertence a uma empresa OU a um usuário (exclusivo)
ALTER TABLE TB0007_PROJECT
ADD CONSTRAINT chk_project_owner CHECK (
    (C0007_COMPANY_ID IS NOT NULL AND C0007_USER_ID IS NULL)
    OR (C0007_COMPANY_ID IS NULL AND C0007_USER_ID IS NOT NULL)
);

-- Todo projeto tem um cliente
ALTER TABLE TB0007_PROJECT ADD COLUMN C0007_CLIENT_NAME VARCHAR(200);
UPDATE TB0007_PROJECT SET C0007_CLIENT_NAME = 'N/A' WHERE C0007_CLIENT_NAME IS NULL;
ALTER TABLE TB0007_PROJECT ALTER COLUMN C0007_CLIENT_NAME SET NOT NULL;
ALTER TABLE TB0007_PROJECT
ADD CONSTRAINT chk_project_client_name_length CHECK (LENGTH(TRIM(C0007_CLIENT_NAME)) >= 2);

CREATE INDEX IX0007_USER_ID ON TB0007_PROJECT (C0007_USER_ID);

-- Índice único: não pode haver dois projetos ativos com o mesmo nome para o mesmo usuário
CREATE UNIQUE INDEX IX0007_USER_NAME_UNIQUE
ON TB0007_PROJECT (C0007_USER_ID, LOWER(C0007_NAME))
WHERE C0007_ACTIVE = TRUE AND C0007_USER_ID IS NOT NULL;

COMMENT ON COLUMN TB0007_PROJECT.C0007_COMPANY_ID IS 'ID da empresa à qual o projeto pertence (NULL = projeto pessoal)';
COMMENT ON COLUMN TB0007_PROJECT.C0007_USER_ID IS 'ID do usuário dono do projeto pessoal (NULL = projeto de empresa)';
COMMENT ON COLUMN TB0007_PROJECT.C0007_CLIENT_NAME IS 'Nome do cliente do projeto (obrigatório)';
