-- Ajustar TB0008_TIME_ENTRY: entry vira container de sessões
ALTER TABLE TB0008_TIME_ENTRY ADD COLUMN C0008_NAME VARCHAR(200);
UPDATE TB0008_TIME_ENTRY SET C0008_NAME = 'Time entry' WHERE C0008_NAME IS NULL;
ALTER TABLE TB0008_TIME_ENTRY ALTER COLUMN C0008_NAME SET NOT NULL;

ALTER TABLE TB0008_TIME_ENTRY ALTER COLUMN C0008_PROJECT_ID SET NOT NULL;

ALTER TABLE TB0008_TIME_ENTRY DROP CONSTRAINT chk_entry_status;
ALTER TABLE TB0008_TIME_ENTRY DROP CONSTRAINT chk_end_after_start;
ALTER TABLE TB0008_TIME_ENTRY DROP CONSTRAINT chk_duration_positive;
ALTER TABLE TB0008_TIME_ENTRY DROP CONSTRAINT chk_team_requires_company;
ALTER TABLE TB0008_TIME_ENTRY DROP CONSTRAINT chk_project_requires_company;
ALTER TABLE TB0008_TIME_ENTRY DROP CONSTRAINT fk_entry_team;

DROP INDEX IX0008_USER_ACTIVE_ENTRY;
DROP INDEX IX0008_STATUS;
DROP INDEX IX0008_TEAM_ID;
DROP INDEX IX0008_TEAM_START;
DROP INDEX IX0008_START_TIME;
DROP INDEX IX0008_USER_STATUS_START;

ALTER TABLE TB0008_TIME_ENTRY DROP COLUMN C0008_TEAM_ID;
ALTER TABLE TB0008_TIME_ENTRY DROP COLUMN C0008_TAGS;
ALTER TABLE TB0008_TIME_ENTRY DROP COLUMN C0008_STATUS;
ALTER TABLE TB0008_TIME_ENTRY DROP COLUMN C0008_START_TIME;
ALTER TABLE TB0008_TIME_ENTRY DROP COLUMN C0008_END_TIME;
ALTER TABLE TB0008_TIME_ENTRY DROP COLUMN C0008_DURATION_SECONDS;

CREATE INDEX IX0008_PROJECT_USER ON TB0008_TIME_ENTRY (C0008_PROJECT_ID, C0008_USER_ID);
CREATE INDEX IX0008_USER_COMPANY ON TB0008_TIME_ENTRY (C0008_USER_ID, C0008_COMPANY_ID);

COMMENT ON COLUMN TB0008_TIME_ENTRY.C0008_NAME IS 'Nome da entrada de tempo (tarefa)';
COMMENT ON COLUMN TB0008_TIME_ENTRY.C0008_COMPANY_ID IS 'ID da empresa (denormalizado do projeto - NULL para projeto pessoal)';
COMMENT ON COLUMN TB0008_TIME_ENTRY.C0008_PROJECT_ID IS 'ID do projeto (obrigatorio - empresa ou pessoal)';

-- Criar Sequence
CREATE SEQUENCE seq_tb0013_time_entry_session START 1;

-- Criar Tabela (sessões de tempo dentro de uma entry - end NULL = timer rodando)
CREATE TABLE TB0013_TIME_ENTRY_SESSION (
    C0013_SESSION_ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    C0013_ENTRY_ID UUID NOT NULL,
    C0013_USER_ID UUID NOT NULL,
    C0013_START_TIME TIMESTAMP WITH TIME ZONE NOT NULL,
    C0013_END_TIME TIMESTAMP WITH TIME ZONE,
    C0013_DESCRIPTION TEXT,
    C0013_ACTIVE BOOLEAN DEFAULT TRUE NOT NULL,
    C0013_CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    C0013_UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    C0013_CREATED_BY UUID NOT NULL,
    C0013_UPDATED_BY UUID NOT NULL,
    C0013_SQ_ID INT NOT NULL DEFAULT nextval('seq_tb0013_time_entry_session'),
    CONSTRAINT chk_session_end_after_start CHECK (C0013_END_TIME IS NULL OR C0013_END_TIME > C0013_START_TIME),
    CONSTRAINT fk_session_entry FOREIGN KEY (C0013_ENTRY_ID)
        REFERENCES TB0008_TIME_ENTRY(C0008_ENTRY_ID) ON DELETE CASCADE,
    CONSTRAINT fk_session_user FOREIGN KEY (C0013_USER_ID)
        REFERENCES TB0002_USER_AUTH(C0002_USER_ID),
    CONSTRAINT fk_session_created_by FOREIGN KEY (C0013_CREATED_BY)
        REFERENCES TB0002_USER_AUTH(C0002_USER_ID),
    CONSTRAINT fk_session_updated_by FOREIGN KEY (C0013_UPDATED_BY)
        REFERENCES TB0002_USER_AUTH(C0002_USER_ID)
);

-- Criar Índices
CREATE UNIQUE INDEX IX0013_SQ_ID ON TB0013_TIME_ENTRY_SESSION (C0013_SQ_ID);
CREATE INDEX IX0013_ENTRY_ID ON TB0013_TIME_ENTRY_SESSION (C0013_ENTRY_ID);
CREATE INDEX IX0013_USER_START ON TB0013_TIME_ENTRY_SESSION (C0013_USER_ID, C0013_START_TIME DESC);
CREATE INDEX IX0013_ACTIVE ON TB0013_TIME_ENTRY_SESSION (C0013_ACTIVE) WHERE C0013_ACTIVE = TRUE;
CREATE INDEX IX0013_CREATED_BY ON TB0013_TIME_ENTRY_SESSION (C0013_CREATED_BY);

-- Índice crítico: apenas 1 timer rodando por usuário
CREATE UNIQUE INDEX IX0013_USER_RUNNING_SESSION
ON TB0013_TIME_ENTRY_SESSION (C0013_USER_ID)
WHERE C0013_END_TIME IS NULL AND C0013_ACTIVE = TRUE;

-- Adicionar Comentários
COMMENT ON TABLE TB0013_TIME_ENTRY_SESSION IS 'Sessões (blocos) de tempo dentro de uma time entry';
COMMENT ON COLUMN TB0013_TIME_ENTRY_SESSION.C0013_SESSION_ID IS 'Identificador único da sessão';
COMMENT ON COLUMN TB0013_TIME_ENTRY_SESSION.C0013_ENTRY_ID IS 'ID da entry à qual a sessão pertence';
COMMENT ON COLUMN TB0013_TIME_ENTRY_SESSION.C0013_USER_ID IS 'ID do usuário (denormalizado da entry)';
COMMENT ON COLUMN TB0013_TIME_ENTRY_SESSION.C0013_START_TIME IS 'Data e hora de início da sessão';
COMMENT ON COLUMN TB0013_TIME_ENTRY_SESSION.C0013_END_TIME IS 'Data e hora de término (NULL = timer rodando)';
COMMENT ON COLUMN TB0013_TIME_ENTRY_SESSION.C0013_DESCRIPTION IS 'Descrição da sessão';
COMMENT ON COLUMN TB0013_TIME_ENTRY_SESSION.C0013_ACTIVE IS 'Indica se a sessão está ativa (soft delete)';
COMMENT ON COLUMN TB0013_TIME_ENTRY_SESSION.C0013_SQ_ID IS 'ID sequencial numérico';

-- Conceder Permissões
GRANT SELECT, INSERT, UPDATE, DELETE ON TB0013_TIME_ENTRY_SESSION TO "TIME-TRACKER-API";
GRANT USAGE, SELECT ON SEQUENCE seq_tb0013_time_entry_session TO "TIME-TRACKER-API";

-- Criar Sequence
CREATE SEQUENCE seq_tb0014_tag START 1;

-- Criar Tabela (tags do usuário com cor - reusáveis entre entries)
CREATE TABLE TB0014_TAG (
    C0014_TAG_ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    C0014_USER_ID UUID NOT NULL,
    C0014_NAME VARCHAR(50) NOT NULL,
    C0014_COLOR VARCHAR(7) NOT NULL,
    C0014_ACTIVE BOOLEAN DEFAULT TRUE NOT NULL,
    C0014_CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    C0014_UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    C0014_CREATED_BY UUID NOT NULL,
    C0014_UPDATED_BY UUID NOT NULL,
    C0014_SQ_ID INT NOT NULL DEFAULT nextval('seq_tb0014_tag'),
    CONSTRAINT chk_tag_color CHECK (C0014_COLOR ~ '^#[0-9A-Fa-f]{6}$'),
    CONSTRAINT fk_tag_user FOREIGN KEY (C0014_USER_ID)
        REFERENCES TB0002_USER_AUTH(C0002_USER_ID),
    CONSTRAINT fk_tag_created_by FOREIGN KEY (C0014_CREATED_BY)
        REFERENCES TB0002_USER_AUTH(C0002_USER_ID),
    CONSTRAINT fk_tag_updated_by FOREIGN KEY (C0014_UPDATED_BY)
        REFERENCES TB0002_USER_AUTH(C0002_USER_ID)
);

-- Criar Índices
CREATE UNIQUE INDEX IX0014_SQ_ID ON TB0014_TAG (C0014_SQ_ID);
CREATE INDEX IX0014_USER_ID ON TB0014_TAG (C0014_USER_ID);
CREATE INDEX IX0014_ACTIVE ON TB0014_TAG (C0014_ACTIVE) WHERE C0014_ACTIVE = TRUE;

-- Índice único: nome de tag único por usuário (case-insensitive)
CREATE UNIQUE INDEX IX0014_USER_NAME_UNIQUE
ON TB0014_TAG (C0014_USER_ID, LOWER(C0014_NAME))
WHERE C0014_ACTIVE = TRUE;

-- Adicionar Comentários
COMMENT ON TABLE TB0014_TAG IS 'Tags do usuário para categorização de time entries';
COMMENT ON COLUMN TB0014_TAG.C0014_TAG_ID IS 'Identificador único da tag';
COMMENT ON COLUMN TB0014_TAG.C0014_USER_ID IS 'ID do usuário dono da tag';
COMMENT ON COLUMN TB0014_TAG.C0014_NAME IS 'Nome da tag';
COMMENT ON COLUMN TB0014_TAG.C0014_COLOR IS 'Cor da tag em hexadecimal (#RRGGBB)';
COMMENT ON COLUMN TB0014_TAG.C0014_SQ_ID IS 'ID sequencial numérico';

-- Conceder Permissões
GRANT SELECT, INSERT, UPDATE, DELETE ON TB0014_TAG TO "TIME-TRACKER-API";
GRANT USAGE, SELECT ON SEQUENCE seq_tb0014_tag TO "TIME-TRACKER-API";

-- Criar Sequence
CREATE SEQUENCE seq_tb0015_time_entry_tag START 1;

-- Criar Tabela (relacionamento N:N entre entries e tags)
CREATE TABLE TB0015_TIME_ENTRY_TAG (
    C0015_ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    C0015_ENTRY_ID UUID NOT NULL,
    C0015_TAG_ID UUID NOT NULL,
    C0015_ACTIVE BOOLEAN DEFAULT TRUE NOT NULL,
    C0015_CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    C0015_UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    C0015_CREATED_BY UUID NOT NULL,
    C0015_UPDATED_BY UUID NOT NULL,
    C0015_SQ_ID INT NOT NULL DEFAULT nextval('seq_tb0015_time_entry_tag'),
    CONSTRAINT fk_entry_tag_entry FOREIGN KEY (C0015_ENTRY_ID)
        REFERENCES TB0008_TIME_ENTRY(C0008_ENTRY_ID) ON DELETE CASCADE,
    CONSTRAINT fk_entry_tag_tag FOREIGN KEY (C0015_TAG_ID)
        REFERENCES TB0014_TAG(C0014_TAG_ID) ON DELETE CASCADE,
    CONSTRAINT fk_entry_tag_created_by FOREIGN KEY (C0015_CREATED_BY)
        REFERENCES TB0002_USER_AUTH(C0002_USER_ID),
    CONSTRAINT fk_entry_tag_updated_by FOREIGN KEY (C0015_UPDATED_BY)
        REFERENCES TB0002_USER_AUTH(C0002_USER_ID)
);

-- Criar Índices
CREATE UNIQUE INDEX IX0015_SQ_ID ON TB0015_TIME_ENTRY_TAG (C0015_SQ_ID);
CREATE INDEX IX0015_ENTRY_ID ON TB0015_TIME_ENTRY_TAG (C0015_ENTRY_ID);
CREATE INDEX IX0015_TAG_ID ON TB0015_TIME_ENTRY_TAG (C0015_TAG_ID);
CREATE INDEX IX0015_ACTIVE ON TB0015_TIME_ENTRY_TAG (C0015_ACTIVE) WHERE C0015_ACTIVE = TRUE;

-- Índice único: uma entry não pode ter a mesma tag duplicada
CREATE UNIQUE INDEX IX0015_ENTRY_TAG_UNIQUE
ON TB0015_TIME_ENTRY_TAG (C0015_ENTRY_ID, C0015_TAG_ID)
WHERE C0015_ACTIVE = TRUE;

-- Adicionar Comentários
COMMENT ON TABLE TB0015_TIME_ENTRY_TAG IS 'Relacionamento N:N entre time entries e tags';
COMMENT ON COLUMN TB0015_TIME_ENTRY_TAG.C0015_ENTRY_ID IS 'ID da entry';
COMMENT ON COLUMN TB0015_TIME_ENTRY_TAG.C0015_TAG_ID IS 'ID da tag';
COMMENT ON COLUMN TB0015_TIME_ENTRY_TAG.C0015_SQ_ID IS 'ID sequencial numérico';

-- Conceder Permissões
GRANT SELECT, INSERT, UPDATE, DELETE ON TB0015_TIME_ENTRY_TAG TO "TIME-TRACKER-API";
GRANT USAGE, SELECT ON SEQUENCE seq_tb0015_time_entry_tag TO "TIME-TRACKER-API";
