CREATE SEQUENCE seq_TB0002_USER_AUTH START 1;

CREATE TABLE TB0002_USER_AUTH (
    C0002_USER_ID UUID PRIMARY KEY, -- Mesmo ID da TB0001_PERSON correspondente (definido pela aplicação)
    C0002_USERNAME TEXT NOT NULL,
    C0002_USERNAME_HASH VARCHAR(64),
    C0002_PASSWORD_HASH VARCHAR(512) NOT NULL,
    C0002_PASSWORD_SALT VARCHAR(512) NOT NULL,
    C0002_ACCESS_TOKEN VARCHAR(512),
    C0002_CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    C0002_UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    C0002_ACTIVE BOOLEAN DEFAULT TRUE NOT NULL,
    C0002_FAILED_ATTEMPTS INT DEFAULT 0 NOT NULL,
    C0002_LAST_PASSWORD_CHANGE TIMESTAMP WITH TIME ZONE,
    C0002_PASSWORD_RESET_REQUESTED BOOLEAN DEFAULT FALSE NOT NULL,
    C0002_LAST_PASSWORD_RESET_REQUEST TIMESTAMP WITH TIME ZONE,
    C0002_LAST_LOGIN TIMESTAMP WITH TIME ZONE,
    C0002_SQ_ID INT NOT NULL DEFAULT nextval('seq_TB0002_USER_AUTH'),
    C0002_USER_CONFIRMED BOOLEAN DEFAULT FALSE NOT NULL,
    C0002_ROLE VARCHAR(50) DEFAULT 'USER' NOT NULL,
    CONSTRAINT chk_failed_attempts CHECK (C0002_FAILED_ATTEMPTS >= 0),
    CONSTRAINT chk_role CHECK (C0002_ROLE IN ('USER', 'ADMINISTRATOR', 'MODERATOR')),
    CONSTRAINT fk_user_id FOREIGN KEY (C0002_USER_ID) REFERENCES TB0001_PERSON(C0001_ID)
);

CREATE UNIQUE INDEX IX0002_USERNAME_HASH ON TB0002_USER_AUTH (C0002_USERNAME_HASH);
CREATE UNIQUE INDEX IX0002_SQ_ID ON TB0002_USER_AUTH (C0002_SQ_ID);
CREATE INDEX IX0002_ACTIVE ON TB0002_USER_AUTH (C0002_ACTIVE) WHERE C0002_ACTIVE = TRUE;
CREATE INDEX IX0002_CREATED_AT ON TB0002_USER_AUTH (C0002_CREATED_AT DESC);

COMMENT ON TABLE TB0002_USER_AUTH IS 'Tabela de autenticação de usuários';
COMMENT ON COLUMN TB0002_USER_AUTH.C0002_USER_ID IS 'Identificador único do usuário, compartilhado com TB0001 obrigatoriamente, definido a nível de aplicação';
COMMENT ON COLUMN TB0002_USER_AUTH.C0002_USERNAME IS 'Nome de usuário (criptografado)';
COMMENT ON COLUMN TB0002_USER_AUTH.C0002_USERNAME_HASH IS 'Hash do username para busca exata';
COMMENT ON COLUMN TB0002_USER_AUTH.C0002_PASSWORD_HASH IS 'Hash da senha criptografada';
COMMENT ON COLUMN TB0002_USER_AUTH.C0002_PASSWORD_SALT IS 'Salt utilizado na criptografia da senha';
COMMENT ON COLUMN TB0002_USER_AUTH.C0002_ACCESS_TOKEN IS 'Token de primeiro acesso ou recuperação de senha';
COMMENT ON COLUMN TB0002_USER_AUTH.C0002_LAST_PASSWORD_CHANGE IS 'Data e hora da última alteração de senha';
COMMENT ON COLUMN TB0002_USER_AUTH.C0002_PASSWORD_RESET_REQUESTED IS 'Indica se há uma solicitação de redefinição de senha pendente';
COMMENT ON COLUMN TB0002_USER_AUTH.C0002_LAST_PASSWORD_RESET_REQUEST IS 'Data e hora da última solicitação de redefinição de senha';
COMMENT ON COLUMN TB0002_USER_AUTH.C0002_SQ_ID IS 'ID sequencial numérico';
COMMENT ON COLUMN TB0002_USER_AUTH.C0002_FAILED_ATTEMPTS IS 'Contador de tentativas de login falhadas';
COMMENT ON COLUMN TB0002_USER_AUTH.C0002_USER_CONFIRMED IS 'Indica se o usuário confirmou o cadastro via email';
COMMENT ON COLUMN TB0002_USER_AUTH.C0002_ROLE IS 'Função do usuário';

GRANT SELECT, INSERT, UPDATE, DELETE ON TB0002_USER_AUTH TO "TIME-TRACKER-API";
GRANT USAGE, SELECT ON SEQUENCE seq_TB0002_USER_AUTH TO "TIME-TRACKER-API";

-- Resolve dependência circular: TB0001_PERSON referencia TB0002_USER_AUTH para audit fields
ALTER TABLE TB0001_PERSON
ADD COLUMN C0001_CREATED_BY UUID,
ADD COLUMN C0001_UPDATED_BY UUID;

ALTER TABLE TB0001_PERSON
ADD CONSTRAINT fk_person_created_by FOREIGN KEY (C0001_CREATED_BY)
    REFERENCES TB0002_USER_AUTH(C0002_USER_ID),
ADD CONSTRAINT fk_person_updated_by FOREIGN KEY (C0001_UPDATED_BY)
    REFERENCES TB0002_USER_AUTH(C0002_USER_ID);

CREATE INDEX IX0001_CREATED_BY ON TB0001_PERSON(C0001_CREATED_BY);
CREATE INDEX IX0001_UPDATED_BY ON TB0001_PERSON(C0001_UPDATED_BY);

COMMENT ON COLUMN TB0001_PERSON.C0001_CREATED_BY IS 'UserAuth que criou o registro (pode ser NULL na criação inicial)';
COMMENT ON COLUMN TB0001_PERSON.C0001_UPDATED_BY IS 'UserAuth que atualizou o registro pela última vez';
