CREATE SEQUENCE seq_tb0004_user_session START 1;

CREATE TABLE TB0004_USER_SESSION (
    C0004_SESSION_ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    C0004_USER_ID UUID NOT NULL,
    C0004_REFRESH_TOKEN TEXT NOT NULL,
    C0004_REFRESH_TOKEN_HASH VARCHAR(64) NOT NULL,
    C0004_REFRESH_TOKEN_EXPIRY TIMESTAMP WITH TIME ZONE NOT NULL,
    C0004_DEVICE_INFO VARCHAR(255),
    C0004_IP_ADDRESS VARCHAR(45),
    C0004_USER_AGENT VARCHAR(500),
    C0004_CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    C0004_UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    C0004_CREATED_BY UUID NOT NULL,
    C0004_UPDATED_BY UUID NOT NULL,
    C0004_ACTIVE BOOLEAN DEFAULT TRUE NOT NULL,
    C0004_LAST_ACTIVITY_AT TIMESTAMP WITH TIME ZONE,
    C0004_SQ_ID INT NOT NULL DEFAULT nextval('seq_tb0004_user_session'),
    CONSTRAINT fk_user_session_user_auth FOREIGN KEY (C0004_USER_ID)
        REFERENCES TB0002_USER_AUTH(C0002_USER_ID) ON DELETE CASCADE,
    CONSTRAINT fk_user_session_created_by FOREIGN KEY (C0004_CREATED_BY)
        REFERENCES TB0002_USER_AUTH(C0002_USER_ID),
    CONSTRAINT fk_user_session_updated_by FOREIGN KEY (C0004_UPDATED_BY)
        REFERENCES TB0002_USER_AUTH(C0002_USER_ID)
);

CREATE UNIQUE INDEX IX0004_SQ_ID ON TB0004_USER_SESSION(C0004_SQ_ID);
CREATE INDEX IX0004_USER_ID ON TB0004_USER_SESSION(C0004_USER_ID);
CREATE INDEX IX0004_REFRESH_TOKEN ON TB0004_USER_SESSION(C0004_REFRESH_TOKEN);
CREATE INDEX IX0004_REFRESH_TOKEN_HASH ON TB0004_USER_SESSION(C0004_REFRESH_TOKEN_HASH);
CREATE INDEX IX0004_ACTIVE ON TB0004_USER_SESSION(C0004_ACTIVE) WHERE C0004_ACTIVE = TRUE;
CREATE INDEX IX0004_EXPIRY ON TB0004_USER_SESSION(C0004_REFRESH_TOKEN_EXPIRY);
CREATE INDEX IX0004_CREATED_BY ON TB0004_USER_SESSION(C0004_CREATED_BY);
CREATE INDEX IX0004_UPDATED_BY ON TB0004_USER_SESSION(C0004_UPDATED_BY);

COMMENT ON TABLE TB0004_USER_SESSION IS 'Tabela de sessões de usuário e refresh tokens';
COMMENT ON COLUMN TB0004_USER_SESSION.C0004_SESSION_ID IS 'Identificador único da sessão';
COMMENT ON COLUMN TB0004_USER_SESSION.C0004_SQ_ID IS 'ID sequencial numérico';
COMMENT ON COLUMN TB0004_USER_SESSION.C0004_USER_ID IS 'Chave estrangeira para TB0002_USER_AUTH';
COMMENT ON COLUMN TB0004_USER_SESSION.C0004_REFRESH_TOKEN IS 'Refresh token criptografado (JWT)';
COMMENT ON COLUMN TB0004_USER_SESSION.C0004_REFRESH_TOKEN_HASH IS 'Hash SHA-256 do refresh token para busca (não criptografado)';
COMMENT ON COLUMN TB0004_USER_SESSION.C0004_REFRESH_TOKEN_EXPIRY IS 'Data e hora de expiração do refresh token';
COMMENT ON COLUMN TB0004_USER_SESSION.C0004_DEVICE_INFO IS 'Informações do dispositivo (ex: mobile, web)';
COMMENT ON COLUMN TB0004_USER_SESSION.C0004_IP_ADDRESS IS 'Endereço IP da sessão';
COMMENT ON COLUMN TB0004_USER_SESSION.C0004_USER_AGENT IS 'User agent do navegador/aplicativo';
COMMENT ON COLUMN TB0004_USER_SESSION.C0004_CREATED_AT IS 'Data e hora de criação da sessão';
COMMENT ON COLUMN TB0004_USER_SESSION.C0004_UPDATED_AT IS 'Data e hora da última atualização da sessão';
COMMENT ON COLUMN TB0004_USER_SESSION.C0004_CREATED_BY IS 'ID do usuário que criou a sessão';
COMMENT ON COLUMN TB0004_USER_SESSION.C0004_UPDATED_BY IS 'ID do usuário que atualizou a sessão pela última vez';
COMMENT ON COLUMN TB0004_USER_SESSION.C0004_ACTIVE IS 'Indica se a sessão está ativa';
COMMENT ON COLUMN TB0004_USER_SESSION.C0004_LAST_ACTIVITY_AT IS 'Data e hora da última atividade nesta sessão';

GRANT SELECT, INSERT, UPDATE, DELETE ON TB0004_USER_SESSION TO "TIME-TRACKER-API";
GRANT USAGE, SELECT ON SEQUENCE seq_tb0004_user_session TO "TIME-TRACKER-API";
