-- Criar Sequence
CREATE SEQUENCE seq_tb0005_company START 1;

-- Criar Tabela
CREATE TABLE TB0005_COMPANY (
    C0005_COMPANY_ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    C0005_NAME VARCHAR(200) NOT NULL,
    C0005_DESCRIPTION TEXT,
    C0005_TIMEZONE VARCHAR(50) DEFAULT 'America/Sao_Paulo' NOT NULL,
    C0005_ACTIVE BOOLEAN DEFAULT TRUE NOT NULL,
    C0005_CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    C0005_UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    C0005_CREATED_BY UUID NOT NULL,
    C0005_UPDATED_BY UUID NOT NULL,
    C0005_SQ_ID INT NOT NULL DEFAULT nextval('seq_tb0005_company'),
    CONSTRAINT chk_company_name_length CHECK (LENGTH(TRIM(C0005_NAME)) >= 2),
    CONSTRAINT fk_company_created_by FOREIGN KEY (C0005_CREATED_BY)
        REFERENCES TB0002_USER_AUTH(C0002_USER_ID),
    CONSTRAINT fk_company_updated_by FOREIGN KEY (C0005_UPDATED_BY)
        REFERENCES TB0002_USER_AUTH(C0002_USER_ID)
);

-- Criar Índices
CREATE UNIQUE INDEX IX0005_SQ_ID ON TB0005_COMPANY (C0005_SQ_ID);
CREATE INDEX IX0005_NAME ON TB0005_COMPANY (C0005_NAME);
CREATE INDEX IX0005_ACTIVE ON TB0005_COMPANY (C0005_ACTIVE) WHERE C0005_ACTIVE = TRUE;
CREATE INDEX IX0005_CREATED_BY ON TB0005_COMPANY (C0005_CREATED_BY);
CREATE INDEX IX0005_CREATED_AT ON TB0005_COMPANY (C0005_CREATED_AT DESC);

-- Adicionar Comentários
COMMENT ON TABLE TB0005_COMPANY IS 'Tabela de empresas/organizações do sistema de time tracking';
COMMENT ON COLUMN TB0005_COMPANY.C0005_COMPANY_ID IS 'Identificador único da empresa';
COMMENT ON COLUMN TB0005_COMPANY.C0005_NAME IS 'Nome da empresa';
COMMENT ON COLUMN TB0005_COMPANY.C0005_DESCRIPTION IS 'Descrição da empresa';
COMMENT ON COLUMN TB0005_COMPANY.C0005_TIMEZONE IS 'Fuso horário padrão da empresa (formato IANA)';
COMMENT ON COLUMN TB0005_COMPANY.C0005_ACTIVE IS 'Indica se a empresa está ativa';
COMMENT ON COLUMN TB0005_COMPANY.C0005_CREATED_AT IS 'Data e hora de criação do registro';
COMMENT ON COLUMN TB0005_COMPANY.C0005_UPDATED_AT IS 'Data e hora da última atualização do registro';
COMMENT ON COLUMN TB0005_COMPANY.C0005_CREATED_BY IS 'ID do usuário que criou o registro';
COMMENT ON COLUMN TB0005_COMPANY.C0005_UPDATED_BY IS 'ID do usuário que atualizou o registro pela última vez';
COMMENT ON COLUMN TB0005_COMPANY.C0005_SQ_ID IS 'ID sequencial numérico';

-- Conceder Permissões
GRANT SELECT, INSERT, UPDATE, DELETE ON TB0005_COMPANY TO "TIME-TRACKER-API";
GRANT USAGE, SELECT ON SEQUENCE seq_tb0005_company TO "TIME-TRACKER-API";
