-- Criar Sequence
CREATE SEQUENCE seq_tb0007_project START 1;

-- Criar Tabela (FLEXÍVEL - projeto pode ser vinculado à empresa OU ao time)
CREATE TABLE TB0007_PROJECT (
    C0007_PROJECT_ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    C0007_COMPANY_ID UUID NOT NULL,  -- Sempre vinculado à empresa
    C0007_TEAM_ID UUID,              -- OPCIONAL (NULL = projeto direto da empresa)
    C0007_NAME VARCHAR(200) NOT NULL,
    C0007_DESCRIPTION TEXT,
    C0007_STATUS VARCHAR(20) DEFAULT 'ACTIVE' NOT NULL,
    C0007_START_DATE DATE,
    C0007_END_DATE DATE,
    C0007_ACTIVE BOOLEAN DEFAULT TRUE NOT NULL,
    C0007_CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    C0007_UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    C0007_CREATED_BY UUID NOT NULL,
    C0007_UPDATED_BY UUID NOT NULL,
    C0007_SQ_ID INT NOT NULL DEFAULT nextval('seq_tb0007_project'),
    CONSTRAINT chk_project_name_length CHECK (LENGTH(TRIM(C0007_NAME)) >= 2),
    CONSTRAINT chk_project_status CHECK (C0007_STATUS IN ('ACTIVE', 'ARCHIVED', 'COMPLETED')),
    CONSTRAINT chk_project_dates CHECK (C0007_END_DATE IS NULL OR C0007_END_DATE >= C0007_START_DATE),
    CONSTRAINT fk_project_company FOREIGN KEY (C0007_COMPANY_ID)
        REFERENCES TB0005_COMPANY(C0005_COMPANY_ID) ON DELETE CASCADE,
    CONSTRAINT fk_project_team FOREIGN KEY (C0007_TEAM_ID)
        REFERENCES TB0006_TEAM(C0006_TEAM_ID) ON DELETE CASCADE,
    CONSTRAINT fk_project_created_by FOREIGN KEY (C0007_CREATED_BY)
        REFERENCES TB0002_USER_AUTH(C0002_USER_ID),
    CONSTRAINT fk_project_updated_by FOREIGN KEY (C0007_UPDATED_BY)
        REFERENCES TB0002_USER_AUTH(C0002_USER_ID)
);

-- Criar Índices
CREATE UNIQUE INDEX IX0007_SQ_ID ON TB0007_PROJECT (C0007_SQ_ID);
CREATE INDEX IX0007_COMPANY_ID ON TB0007_PROJECT (C0007_COMPANY_ID);
CREATE INDEX IX0007_TEAM_ID ON TB0007_PROJECT (C0007_TEAM_ID);
CREATE INDEX IX0007_NAME ON TB0007_PROJECT (C0007_NAME);
CREATE INDEX IX0007_STATUS ON TB0007_PROJECT (C0007_STATUS);
CREATE INDEX IX0007_ACTIVE ON TB0007_PROJECT (C0007_ACTIVE) WHERE C0007_ACTIVE = TRUE;
CREATE INDEX IX0007_CREATED_BY ON TB0007_PROJECT (C0007_CREATED_BY);
CREATE INDEX IX0007_CREATED_AT ON TB0007_PROJECT (C0007_CREATED_AT DESC);

-- Adicionar Comentários
COMMENT ON TABLE TB0007_PROJECT IS 'Tabela de projetos do sistema de time tracking';
COMMENT ON COLUMN TB0007_PROJECT.C0007_PROJECT_ID IS 'Identificador único do projeto';
COMMENT ON COLUMN TB0007_PROJECT.C0007_COMPANY_ID IS 'ID da empresa à qual o projeto pertence (obrigatório)';
COMMENT ON COLUMN TB0007_PROJECT.C0007_TEAM_ID IS 'ID do time responsável pelo projeto (OPCIONAL)';
COMMENT ON COLUMN TB0007_PROJECT.C0007_NAME IS 'Nome do projeto';
COMMENT ON COLUMN TB0007_PROJECT.C0007_DESCRIPTION IS 'Descrição do projeto';
COMMENT ON COLUMN TB0007_PROJECT.C0007_STATUS IS 'Status do projeto (ACTIVE, ARCHIVED, COMPLETED)';
COMMENT ON COLUMN TB0007_PROJECT.C0007_START_DATE IS 'Data de início do projeto';
COMMENT ON COLUMN TB0007_PROJECT.C0007_END_DATE IS 'Data de término do projeto';
COMMENT ON COLUMN TB0007_PROJECT.C0007_ACTIVE IS 'Indica se o projeto está ativo (soft delete)';
COMMENT ON COLUMN TB0007_PROJECT.C0007_CREATED_AT IS 'Data e hora de criação do registro';
COMMENT ON COLUMN TB0007_PROJECT.C0007_UPDATED_AT IS 'Data e hora da última atualização do registro';
COMMENT ON COLUMN TB0007_PROJECT.C0007_CREATED_BY IS 'ID do usuário que criou o registro';
COMMENT ON COLUMN TB0007_PROJECT.C0007_UPDATED_BY IS 'ID do usuário que atualizou o registro pela última vez';
COMMENT ON COLUMN TB0007_PROJECT.C0007_SQ_ID IS 'ID sequencial numérico';

-- Conceder Permissões
GRANT SELECT, INSERT, UPDATE, DELETE ON TB0007_PROJECT TO "TIME-TRACKER-API";
GRANT USAGE, SELECT ON SEQUENCE seq_tb0007_project TO "TIME-TRACKER-API";
